### ISSUE TITLE
オープンデータのCSVをjsonに自動で変換するようにしたい

### ISSUE THREAD

**Issue by euledge** [code-for-hamamatsu/vaccinecert-faq#11]
## 改善詳細 / Details of Improvement
- ~~スプレッドシートAPIで出力されるJSONの形式を変換して本ページに使用できる形にして受け取れるようにしてほしい。~~
- オープンデータ  https://cio.go.jp/sites/default/files/uploads/documents/VaccinecertFAQ.csv からjsonに変換する
- データにはヘッダがないので自分でヘッダ追加する必要がある

## 期待する見せ方・挙動 / Expected behavior
- 現在表示に最低限必要な項目はカテゴリ、質問、回答を以下の形にしたもの

```json
[
 {
   "カテゴリ": "xxxxxxx",
   "質問": "xxxxxxx",
   "回答": "xxxxxxx",
 },
 {
   "カテゴリ": "yyyyy",
   "質問": "yyyyyy",
   "回答": "yyyyy",
 },
]
```

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by euledge** [comment]
データはオープンデータカタログにアップされてるCSVから取得してJSON変換するでよいことになりました

**Comment by hmatsu47** [comment]
CSV の 1 行目に項目名が入っていないようですが、このままだとすると項目名は CSV 外から与えてあげる必要がありそうですね。

**Comment by euledge** [comment]
#60 のIssueにとりあえずの変換コマンド書いておきました

**Comment by euledge** [comment]
issue #52 でurlリンクを表示したいんですが、url文字列の前後の全角丸かっこを半角丸かっこに置換してくれると嬉しいです。
（http://hoge.com）→ (http://hoge.com)
httpsの場合も同様
