### ISSUE TITLE
TOPページ　subtitle　修正検討　

### ISSUE THREAD

**Issue by NonbiriTarsan** [code-for-hamamatsu/vaccinecert-faq#13]
## 改善詳細 / Details of Improvement

subtitle = "Find advice and answers from our support team fast or get in touch"
「サポートチームからのアドバイスや回答をすぐに見つけることができ、連絡を取ることができます。」
いらないのでは。

## スクリーンショット / Screenshot
config.toml　のsubtitleの修正またはコメントアウト

## 期待する見せ方・挙動 / Expected behavior
TOPはシンプル？

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by jacoyutorius** [comment]
確かに不要そうですねぇ
