### ISSUE TITLE
FAQ回答の改行が反映されていない。

### ISSUE THREAD

**Issue by ww2or3ww** [code-for-hamamatsu/vaccinecert-faq#14]
## 改善詳細 / Details of Improvement
- FAQの回答において、改行(¥n)が反映されていない。

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/6513552/145715481-e7cf9d27-cef7-49b9-8594-5fef1be0bd5d.png)
![image](https://user-images.githubusercontent.com/6513552/145715506-f0b74deb-7418-43be-a781-fb3644c2cd8e.png)

## 期待する見せ方・挙動 / Expected behavior
- 改行されたほうがいい？
`div.card-body` に対して `style="white-space:pre-wrap; ` を当てられれば良さそう。
当ててみた様子：
![image](https://user-images.githubusercontent.com/6513552/145716173-4d8263ca-dc7d-4bad-ad16-60c369c1e237.png)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by jacoyutorius** [comment]
個人的には `申し込みができます。` の下はもう一行空けたいw

**Comment by ww2or3ww** [comment]
@jacoyutorius これはデータの問題ですね。
スプレッドシートに改行含めて記載されていた場合、JSONでは `¥n` で表現されるんですけど、それが現状HTMLで表現できていない、という事象になります。
> 個人的には `申し込みができます。` の下はもう一行空けたいw (データの問題ですかね）

**Comment by euledge** [comment]
shortcodesのvaccinefaq.htmlの修正で良いです
