### ISSUE TITLE
当面言語選択のドロップダウンは不要？

### ISSUE THREAD

**Issue by euledge** [code-for-hamamatsu/vaccinecert-faq#15]
## 改善詳細 / Details of Improvement
- 現時点で日本語以外のFAQはできないと思うので下手に選択させても困る

## 期待する見せ方・挙動 / Expected behavior
- 日本語以外の選択肢を消す (config.toml)

## 動作環境・ブラウザ / Environment
すべて

**Comment by jacoyutorius** [comment]
config.tomlの `disableLanguages` で制御できそうですね。
直近のリリースは日本語のみにして、徐々に対応言語増やしていく感じがいいのかな

**Comment by ww2or3ww** [comment]
情報源(翻訳済のワーディング)があるかどうかですよね。
あるなら 日英 くらいは最初からあっても良いかと思いました。

対応する場合の設計としては、以下のような感じになりますかね？
・スプレッドシートは言語ごとにシートを分ける
・JSONも言語ごとにファイルを分ける

**Comment by jacoyutorius** [comment]
機械翻訳でいいならAPIの間にAmazon TranslateかけるLambdaを噛ませちゃってもいいんですけどね〜

**Comment by jacoyutorius** [comment]
データマターなので @poba1031 に投げておきますmm

**Comment by ww2or3ww** [comment]
メモ：
初版は日本語のみのため、(ゆくゆくは復活しますが) 消すことになりました。
