### ISSUE TITLE
各種表示を「ワクチン接種証明アプリFAQ」で統一したい。

### ISSUE THREAD

**Issue by poba1031** [code-for-hamamatsu/vaccinecert-faq#17]
## 改善詳細 / Details of Improvement
- 表示やheadの中のtitleなどを「ワクチン接種証明アプリFAQ」で統一したい。

## スクリーンショット / Screenshot
![Screenshot 2021-12-13 13 13 36](https://user-images.githubusercontent.com/52411688/145751553-ee10b0d7-366a-4cde-b991-c30e9a53f5c0.png)

## 期待する見せ方・挙動 / Expected behavior
- すべての表記表示を「ワクチン接種証明アプリFAQ」で統一

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by euledge** [comment]
正しい表記はこちらになりますね、これで統一します
「新型コロナワクチン接種証明書アプリ」
![image](https://user-images.githubusercontent.com/1209580/146660722-a5c71f95-28ef-4149-93dc-7b4e7891a860.png)

**Comment by euledge** [comment]
iPhone6,7,8 サイズだとタイトル切れちゃうな
![image](https://user-images.githubusercontent.com/1209580/146660983-2ff21d30-314a-4e14-838e-8c43599e13d8.png)

**Comment by euledge** [comment]
まずは用語の統一を優先にして、こちらでいっておきます
![image](https://user-images.githubusercontent.com/1209580/146663586-bbcf0de4-4c3e-49d3-a123-a4c91d207bcb.png)
