### ISSUE TITLE
Aboutページを作成

### ISSUE THREAD

**Issue by euledge** [code-for-hamamatsu/vaccinecert-faq#20]
## 改善詳細 / Details of Improvement
- Aboutページに免責事項、Hugo Theme Dotのライセンスなど載せる

## 期待する見せ方・挙動 / Expected behavior
- xxxx(できるだけ簡潔に/as concise as possible)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by euledge** [comment]
やります

**Comment by euledge** [comment]
Aboutページに書く内容についてまとめてみました
以下の内容を表示させるといいんじゃないかと思いますがどうでしょうか？
@jacoyutorius @ww2or3ww @hmatsu47 @poba1031 

## このサイトについて
このサイトはCode For Hamamatsuが、デジタル庁が公開した [新型コロナワクチン接種証明書アプリ](https://www.digital.go.jp/policies/posts/vaccinecert) のFAQオープンデータを利用したFAQサイトです。

本サイトは [Hugo](https://gohugo.io/)を用いて作成されており、テーマには[Dot Hugo](https://github.com/themefisher/dot-hugo)を使用しています。

## FAQの内容について
FAQに記載される内容は、デジタル庁から公開される内容でありCode For Hamamatsuの意見、見解を表すものではありません。
本サイトに表示されるFAQの内容についてのお問い合わせはデジタル庁の新型コロナワクチン接種証明書アプリのお問い合わせ先〇〇〇〇〇〇〇にお問い合わせください。

## 本サイトのライセンス
本サイトのソースコードは [MITライセンス](https://github.com/code-for-hamamatsu/vaccinecert-faq/blob/main/LICENCE.txt) が適用されます。
本サイトで表示されるFAQの内容の引用、転載、二次利用についてはデジタル庁のコンテンツポリシーに従うものとします。

**Comment by poba1031** [comment]
問い合わせ先は、ヘルプデスクの問い合わせフォームを案内することになる予定です。

**Comment by hmatsu47** [comment]
> 本サイトに表示されるFAQの内容についてのお問い合わせはデジタル庁の新型コロナワクチン接種証明書アプリのお問い合わせ先〇〇〇〇〇〇〇にお問い合わせください。

「お問い合わせ」が 3 回繰り返されると少し冗長な気がしますが、

本サイトに表示されるFAQの内容についての不明点・疑問点等は、こちらにお問い合わせください。

 - 〇〇〇〇〇〇〇

ぐらいで良いんじゃないですかね？

当初は Google Analytics なども入れないですし一旦プライバシーポリシーは無し、で大丈夫ですね。

**Comment by euledge** [comment]
> デジタル庁のコンテンツポリシー
これ本当は違うんですよね、コンテンツポリシーはデジタル庁のサイトにあるコンテンツについてのものなので
ただ今現在オープンカタログに載らない状態で良い感じのものが浮かばなくて...
公開場所はぼやかしたまま、こんな感じにしておこうかな

本サイトで表示されるFAQの内容の引用、転載、二次利用についてはオープンデータの利用条件に従うものとします。
本サイトで使用されるFavicon等の画像は利用許諾を得て使用しています。

**Comment by euledge** [comment]
一旦これでページ作ってみますのでまたその時レビューお願いします

**Comment by ww2or3ww** [comment]
@euledge ありがとうございます！2点ほど感じたことがあります。

１．Code For Hamamatsu いるか？
> このサイトはCode For Hamamatsuが、デジタル庁が公開した、、

→ このサイトはデジタル庁が公開した、、

> デジタル庁から公開される内容でありCode For Hamamatsuの意見、見解を、、

→ デジタル庁から公開された内容です。

最後の方にちょろっと「このサイトは有志により運営されています。」くらいを書いておけばいいかなと感じましたが、どうでしょうか。


２．Hugoやテーマのくだり、あまり(利用者にとって)重要ではないのでは？
> 本サイトは Hugoを用いて作成されており、テーマにはDot Hugoを使用しています。
> 本サイトで使用されるFavicon等の画像は利用許諾を得て使用しています。

この辺の情報も、末尾で良さそうに思いますが、いかがでしょうか。

**Comment by poba1031** [comment]
@ww2or3ww さんの感じでいいと思います。

**Comment by euledge** [comment]
怖い人たちに怯えて、いっぱいエクスキューズ入れて書いちゃいました（笑）
@ww2or3ww  さんの意見採用でやってみますね

**Comment by hmatsu47** [comment]
以前、愛知県の非公式コロナ対策サイトのほうに関わっていたので思い出したのですが、

- 公式（デジ庁）が出す情報について Code for Hamamatsu が問い合わせを受けても困る

のと同じように、

- Q&A の内容そのものではない、サイトの構成などについて公式（デジ庁）の窓口が何か言われても困る

ので、それについて「このサイトは有志により運営されています。」のところで一言触れておいたほうがよさそうな気がしました。

（↓愛知県の非公式コロナ対策サイトはこんな感じになっています。）
![image](https://user-images.githubusercontent.com/35142774/146323438-62639168-1ed2-4197-a059-22b547aba339.png)

https://stopcovid19.code4.nagoya/
https://stopcovid19.code4.nagoya/about

「サイトに対する改善要望等は、（○○○○窓口ではなく）GitHub の Issues へお寄せください」みたいな感じになりますかね？（あまり変なのが来られても困りますけど）

**Comment by jacoyutorius** [comment]
確かに、、

> 窓口の負担は減らしたい

これにはおおいに賛成なので、"GitHub の Issues へお寄せください"でいいと思います。

Code for Nagoyaのを参考にすると↓のようなイメージ？

---

### お問い合わせ先 

サイトに対する改善要望等は GitHub の[Issues]()へお寄せください。

**Comment by euledge** [comment]
Code for Nagoyaのを見て気づいたけど、 今回のは Code for Japanについては書かなくていいのかな？
インフラ面の協力はしてもらってるし
