### ISSUE TITLE
SNSアイコンの設定をしたい

### ISSUE THREAD

**Issue by euledge** [code-for-hamamatsu/vaccinecert-faq#22]
## 改善詳細 / Details of Improvement
- ~SNSアイコンに何を載せるか決めて対応する~
- first release時にはアイコン載せない

## 期待する見せ方・挙動 / Expected behavior
- xxxx(できるだけ簡潔に/as concise as possible)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by euledge** [comment]
このサイトの運営の主体がシビックテック側だとするとソーシャルリンクにデジタル庁のもの載せるのは駄目じゃないかと思ってきた どうでしょう?
@poba1031 @jacoyutorius

**Comment by jacoyutorius** [comment]
確かに、、Githubのやつくらいで良いかもですね
