### ISSUE TITLE
プルリクからのマージの運用ルール決めた方がよい？

### ISSUE THREAD

**Issue by euledge** [code-for-hamamatsu/vaccinecert-faq#25]
## 改善詳細 / Details of Improvement
- デプロイの運用主体がこっちにありそうなので好きな時にできるけど、なるべく変なもの上げないようにはしてきたいのでAmplify のreview機能からのマージをルール決めといたほうがよいと思う。

## 期待する見せ方・挙動 / Expected behavior
- 例えばPRに複数人Reviewer設定してn人のLGTMがあったらマージするとか？ 皆さんのところの運用例参考にしたい

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by euledge** [comment]
そもそも 今マージって誰ができるんだっけ?
@jacoyutorius 

↓ まずはこれやっておこう
https://yourmystar-engineer.hatenablog.jp/entry/2017/05/08/113147

**Comment by jacoyutorius** [comment]
多分ですけど、今cohのowner権限が付いている4名かなと思います
https://github.com/orgs/code-for-hamamatsu/people

> 複数人Reviewer
良さそうですね 👍

**Comment by jacoyutorius** [comment]
`Restrict who can push to matching branches` を設定しました。

![Branch_protection_rule](https://user-images.githubusercontent.com/662084/146175565-cb3e4b6c-1249-468e-a22f-9a8cd8b0e420.jpg)


あと、hmasu47さんをcfhのorganizationsにinviteしています。マージ権限付与したいなと。

取り急ぎ、これまでプルリクを送っている4名に権限付与する感じです。

**Comment by jacoyutorius** [comment]
reviewer複数人は設定できないっぽい・・・？

**Comment by ww2or3ww** [comment]
![image](https://user-images.githubusercontent.com/6513552/146184165-2f16d675-0a02-451b-83b6-bec99126b365.png)

mainブランチに対して require number of approvals before merging = 2 の設定を加えておきました。
(2人のApproveでマージ可の状態になる)

**Comment by jacoyutorius** [comment]
おお！👏

**Comment by euledge** [comment]
gh-pagesへのデプロイで失敗しちゃっているのでもう少し調整します

**Comment by euledge** [comment]
ワイルドカード*はルール消して mainのルールに `Restrict who can push to matching branches` 付けました
これでgh-pagesにはマージできたけどこれでよかったかな？
ワイルドカードでルール作ったのはどんな意図でしたか？

amplify でpreviewできるようになれば github-pagesはいらなくなりそうだけど

**Comment by jacoyutorius** [comment]
ブランチ名のルールが空白だと`Restrict who can push to matching branche` の設定を保存するのに失敗するのでとりあえず入れた感じですね 😓

**Comment by euledge** [comment]
Amplify PreviewにBASIC認証もかけられたので Github Pages お疲れ様でした
とりあえずの運用は流れていきそうなのでクローズします
