### ISSUE TITLE
カテゴリ別ページの更新日を消す

### ISSUE THREAD

**Issue by hmatsu47** [code-for-hamamatsu/vaccinecert-faq#30]
## 改善詳細 / Details of Improvement
- カテゴリ別ページの下に更新日が表示されるが、意味が無さそうなので消す

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/35142774/146305438-0a9b48cf-4afb-45a7-bcd2-a77b7a1264c8.png)

## 期待する見せ方・挙動 / Expected behavior
- 非表示にする
- 意味のある値を埋め込めるようになったら表示するように戻してもよいが、戻すよりも Q&A の各項目にそれぞれ更新日を表示したほうがよさそう。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by euledge** [comment]
Q&Aの更新日表示するのはいいですね。できると思います

**Comment by ww2or3ww** [comment]
> Q&A の各項目にそれぞれ更新日を表示したほうがよさそう。

これは、カテゴリごとにではなく、項目ごとに、というイメージですか？
(回答のワードに含める。)
更新が発生したら、回答のワードに書いてもらっても良いかもしれないですね〜。

**Comment by euledge** [comment]
CSVデータの中に更新日あるからそれ使えばいいと思います。
