### ISSUE TITLE
プレビュー用URLが502エラー

### ISSUE THREAD

**Issue by jacoyutorius** [code-for-hamamatsu/vaccinecert-faq#42]
## 起こっている問題 / The Problem
- プルリク作成後、Amplifyが自動で発行するプレビュー用のURLにアクセスするとページが502エラーになっている
  - 公開用にRoute53の設定をした影響？

## スクリーンショット / Screenshot

<img width="715" alt="ERROR__The_request_could_not_be_satisfied" src="https://user-images.githubusercontent.com/662084/146657599-9ca65bfe-8551-468a-857f-ddc792bcaa9b.png">

## 期待する見せ方・挙動 / Expected Behavior
- プルリクで修正された内容が閲覧できるようにする

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by ww2or3ww** [comment]
@jacoyutorius  これ、ブランチ名が都合悪いみたいです。

fix/#123-test
みたいなブランチ名だと
fix--123-test みたいなサブドメインになると思うのですが、ハイフンが2つ続くのが都合悪いみたい。

fix/123-test
みたいにしてあげると問題事を確認できました。

**Comment by jacoyutorius** [comment]
なるほどです、URLに利用不可能な文字が含まれてるからか。
ブランチ名のルール変えましょうかね。
（実はコロナ対策サイトのころからブランチ名に `#` とか `/` が入っているのが気持ち悪かったんです。。）

`123_test` みたいなのでいい気がするんですがどうでしょうねー

**Comment by ww2or3ww** [comment]
今、機能追加系 と ホットフィックス系 とでプレフィックスを付与するように案内されていますが、
それはそれでいいんじゃないかなと思ってたりしています。
ので、feature/ とかはついててもいいような気はしています。

と、ここまで書いて、東京都の対策サイトは今どうなってるのかと思って見に行ったら
feature/issue-6993-fix-nav-text
このようになってました。

これを真似するでいいんじゃないでしょうか！

**Comment by euledge** [comment]
issue-はなくても数字から始まれば大体Issue番号かなとは思います。
なるべく短くしたい派

**Comment by euledge** [comment]
そして、プレビューURLにはBASIC認証 Done!!
