### ISSUE TITLE
SNSでシェアしたときに、適切に情報が出るようにする

### ISSUE THREAD

**Issue by halsk** [code-for-hamamatsu/vaccinecert-faq#51]
## 改善詳細 / Details of Improvement
- 現状だと、SNSでシェアしたときにURLしか表示されないので、何のサイトかわかりにくい。

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/16509/146667211-91b4c6e7-6449-48ab-9971-cf5bf93eea83.jpeg)

## 期待する見せ方・挙動 / Expected behavior
- サイト名とディスクリプション、サムネイルが表示されるようにしたい

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by hmatsu47** [comment]
- https://gohugo.io/templates/internal#open-graph
- https://gohugo.io/templates/internal#twitter-cards

このあたりの設定ですかね？
（OGP 画像に使うのはアイコン？）

**Comment by ww2or3ww** [comment]
![image](https://user-images.githubusercontent.com/6513552/146674124-29aa9e71-f865-4e39-aca7-cc7a223db44d.png)
This is meta description
もなくしたい。
https://github.com/code-for-hamamatsu/vaccinecert-faq/blob/main/config.toml#L27
> description = "This is meta description"

LINEやSlackで確認。

**Comment by ww2or3ww** [comment]
https://github.com/code-for-hamamatsu/vaccinecert-faq/issues/51#issuecomment-997380090
> This is meta description
> もなくしたい。

とりいそぎ、説明だけのプルリクを発行しました。 https://github.com/code-for-hamamatsu/vaccinecert-faq/pull/53

**Comment by ww2or3ww** [comment]
![image](https://user-images.githubusercontent.com/6513552/146679053-f43f9f38-9eab-4125-8efd-9147afe840cd.png)
done!
