### ISSUE TITLE
URLがテキストになっているのでリンクにしたい

### ISSUE THREAD

**Issue by jacoyutorius** [code-for-hamamatsu/vaccinecert-faq#52]
## 改善詳細 / Details of Improvement
- FAQに含まれるURLがテキスト形式で表示されている

## スクリーンショット / Screenshot

<img width="771" alt="3_このような場合は発行できますか" src="https://user-images.githubusercontent.com/662084/146673748-d566f82e-9513-4138-9ad7-025b99b46f55.png">

## 期待する見せ方・挙動 / Expected behavior

- リンク形式にする

**Comment by euledge** [comment]
出来ちゃったのでやります

**Comment by euledge** [comment]
マークダウンとして認識するから半角()で囲まれればリンクだけど全角（）で囲まれてもダメ
CSVの出力側で対応してもらうか、別の方法考えるしかなさそう
