### ISSUE TITLE
FAQの一つ一つのQAにpermalinkを割り当てる

### ISSUE THREAD

**Issue by halsk** [code-for-hamamatsu/vaccinecert-faq#68]
## 改善詳細 / Details of Improvement
- メール等で質問への回答を提示するときに、URLが必要となると思われる。今はカテゴリごとにURLがあるだけなので、参照しにくい

## 期待する見せ方・挙動 / Expected behavior
- 回答それぞれのページがあり、URLが存在している。質問が後から増加してもURLは変わらないようにしたい。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by euledge** [comment]
@jacoyutorius @ww2or3ww @hmatsu47

カテゴリや順序は変化する可能性もあるから
パーマリンクに使うキーとしては質問文のハッシュ値とかどうでしょうか?

質問文が修正されるケースはあるかも知れないけど、その場合は内容も異なるので別物と見なしてもいい気がします。

CSVからの変換のときに生成しちゃえば良さそう。

**Comment by euledge** [comment]
質問、回答 のペアを1コンテンツにしてページを作って､taxonomiesっていうのに、現在のカテゴリを設定してあげれば、カテゴリ別ページ一覧もできそう、
SEOのことはよくわからないけど、URLにもカテゴリ名が現れるのでGoogleなどの検索にヒットするようになる？
taxonomyの他にも各ページにtagを振る事も出来るみたいなので複数のキーワードで抽出出来そう。

https://hugo-de-blog.com/hugo-taxonomy/

**Comment by hmatsu47** [comment]
12/24 に、

- 接種証明書アプリがインストールできません。「お使いのデバイスはこのバージョンに対応していません。」と表示され**る**。

という質問が追加されましたが、このような軽微なミスの場合は、

- 接種証明書アプリがインストールできません。「お使いのデバイスはこのバージョンに対応していません。」と表示され**ます**。

に直しても以前の識別コードのまま通用させたいのでは？と思いましたが、いかがでしょうか。

（担当の方がお疲れなのか、12/24 追加分は他にも怪しいものがありましたね…）

あと、このパーマリンクを窓口担当の方が容易に使える（転記ミス等が起きにくいフォーマット等）ようにしておくのも大事ですよね。

データからは、今のところ「質問・回答の文章を追記・修正しても順番等を変えても `No` は変えない」運用をされているのが見て取れます。

このあたりは利用される窓口担当の方の要望を聞くことができると決めやすいですね。

**Comment by jacoyutorius** [comment]
（やるかどうか未定ですが）質問単位でのアクセス数集計をしたい場合、ハッシュ値だと結果が見づらいかもですね
 🤔 
各回答には一意となるIDを振ってもらったほうがいいかもなと思いました

**Comment by euledge** [comment]
一意なIDはCSVに記載されるNoという事で決定
