### ISSUE TITLE
カテゴリが変更されても自動的に対応して表示できるようにしたい

### ISSUE THREAD

**Issue by euledge** [code-for-hamamatsu/vaccinecert-faq#9]
## 改善詳細 / Details of Improvement
-  カテゴリが増えたり、変更になったときにコンテンツ自体の変更が必要
-  個別のQAページ生成させてパーマリンクにすることでshareしやすくする #68 
- URLにカテゴリ名を含めることで検索エンジンに見つけやすくする #81
- モブでやってHugoの構造の知見を共有したい

必要なスキル
- python超初心者レベル

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/1209580/145707879-5a6669bd-36b6-40b0-b5c8-59e59eff7a8e.png)

## 期待する見せ方・挙動 / Expected behavior
- 運用次第ではありますが、カテゴリの変更頻度が低ければこのままでもよいと思います。
- できればJSONからカテゴリ抽出して動的に対応したい
  - Hugo自体で難しければGithubActionの間に別言語( pythonやnode ,ruby)でコンテンツ作成してコミットするでもよいと思う

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by jacoyutorius** [comment]
確かに、下手にプログラム組むよりも運用で吸収できるならならそのままでも良い気がしますね

**Comment by euledge** [comment]
Hugoの構造を理解するための題材としてモブでやってみたい
