### ISSUE TITLE
#89 の検索結果画面へのブラウザバック実装

### ISSUE THREAD

**Issue by hmatsu47** [code-for-hamamatsu/vaccinecert-faq#90]
## 改善詳細 / Details of Improvement
- #89 の、

> - 検索結果から個別qaに繊維したときの戻るリンク(<<)がカテゴリーになっている。
　検索結果から飛んだ場合は、「<< 検索結果」のようにしたい。(ブラウザバックと同じ挙動)

を対応する。

## 期待する見せ方・挙動 / Expected behavior
- 「<< 検索結果」
- リンクは `history.back();` に

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by ww2or3ww** [comment]
同じテーマのIssueをちょい遅れで建ててしまいましたので、リンクだけ貼っておき、向こう側はクローズしておきます。
https://github.com/code-for-hamamatsu/vaccinecert-faq/issues/91
