### ISSUE TITLE
カテゴリページから個別Q&Aページへの遷移リンクではなくシェアボタンにした方がよいかも

### ISSUE THREAD

**Issue by euledge** [code-for-hamamatsu/vaccinecert-faq#93]
## 改善詳細 / Details of Improvement

カテゴリページから個別Q&Aページへの遷移をするためのリンクが右下にありますが、

@ww2or3ww  さんが以下で言及しているように、
https://jaws-ug-hamamatsu.slack.com/archives/C0111LQQP71/p1640479555259300?thread_ts=1640394702.218200&cid=C0111LQQP71

ユーザー目線で考えた場合、すでにアコーディオンで回答がオープンになっているのにさらに個別のページを開いても
新たに知りうる情報はないと思うのでクリックする目的があまりないのではないかと思います。
想定される機能としては個別Q&Aに対してリンクをシェアすることのような気がしますので、
このリンクの代わりにシェアさせる機能を持たせた方がよいかと思います。

シェアアイコンにするか、このままリンクにするかは皆さんの意見も聞きたいところです。

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/1209580/147410293-9b837bbb-4315-404f-ae1d-7b8175999a73.png)

## 期待する見せ方・挙動 / Expected behavior
- シェアアイコンの設置を行う

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by ww2or3ww** [comment]
ありがとうございます！
そうなんですよねー。悩みどころです。

シェアボタンにしたとして、そのボタンを押下した際のアクションも悩ましいポイントかと思います。
どのようなアクションをイメージしていましたか？

クリップボードに個別QAページのアドレスを保存(Copy Link)、だけであれば難しくないですが、
(でもそれだと名が体を表しておらず、、)
ちゃんとやろうとすると、メニューを出してCopyLinkとは別に各種SNSアイコン並べて〜とかですかね？

**Comment by hmatsu47** [comment]
これ、今のところ意味は無いのですが、今後

- 形態素解析で文中の語句の一致度が高い順に 3 つ関連 Q&A を表示
- Cookie による

**Comment by euledge** [comment]
リンクをコピーする というアクション
IT系のツールを使い慣れている人向けかなって気がします。コピーしたリンクを何に使うかは自分で決めるっいう点で。
一般的なユーザー的にはSNSでのシェアが前提と考えているかなぁ、
一般的な twitter,facebookとかでシェアさせる機能でも良いのではと思います。

**Comment by hmatsu47** [comment]
ブラウザでのシェア機能ですが、SNS 各サービスが提供している URI を（パラメータ付きで）呼び出すと作ることができそうです。
https://mgmgblog.com/?p=1979

**Comment by euledge** [comment]
アイコンは元のテーマで表示していたと思いますのでSNSシェアするなら使えますね。

**Comment by euledge** [comment]
Twitterはハッシュタグも指定できそうなので良さげです。 twitter,facebook,LINE ができれば良いかなぁ

**Comment by hmatsu47** [comment]
ちなみに、こちらにも関連するのでここに書きますが、 #92 が本番反映したら正常に動きませんでした（リクエストパラメータを付けると CF 側か Amplify かでリクエストパラメータ無しの URL にリダイレクトが掛かる）。

リクエストパラメータではなくてハッシュかパスパラメータなら動きそうですが、こちらの Issue に対応すると、そもそも #92 の対応自体が不要になりそうなので、念のためこちらに書きました。

**Comment by ww2or3ww** [comment]
> 本番反映したら正常に動きませんでした（リクエストパラメータを付けると CF 側か Amplify かでリクエストパラメータ無しの URL にリダイレクトが掛かる）。

ほんとですね。なぜだ、、。

**Comment by ww2or3ww** [comment]
解決しました！
https://github.com/code-for-hamamatsu/vaccinecert-faq/pull/95

**Comment by euledge** [comment]
こんな感じに設置してみます
![image](https://user-images.githubusercontent.com/1209580/147588116-384579b5-6adb-46c2-8381-d943bee4659d.png)

Twitterはこんな感じ
![image](https://user-images.githubusercontent.com/1209580/147585128-4274030e-2e4c-4e34-92f4-3eafd86d49b7.png)

ハッシュタグは他にも設定可能です、いいのがあったらコメントください

**Comment by euledge** [comment]
アイコンはLINEのもの使いたかったのでシェアボタンについてはfontawsome使用しています。
